server {
    listen 80;
    root /usr/share/nginx/html;
    client_max_body_size 51m;
    location /api/ {
        proxy_pass http://api:8080;
        proxy_read_timeout 120s;
    }
    location / { try_files $uri $uri/ /index.html; }
}
