import { useCallback, useEffect, useRef, useState } from 'react';
import { Activity, ArrowDownToLine, BoxSelect, ChevronRight, CircleDot, FlaskConical, FolderOpen, Hand, Image as ImageIcon, Layers3, LoaderCircle, Plus, Play, RotateCcw, Upload, X } from 'lucide-react';
import { api, post } from './api';
import { Viewer } from './Viewer';
import { labels, colors, type Project, type TissueImage, type Roi, type Rect, type Run, type Cell, type Summary, type Review } from './types';
const statuses = {Queued: '排队中', Running: '正在分析', Succeeded: '分析完成', Failed: '分析失败'};
export default function App() {
  const [projects,setProjects] = useState<Project[]>([]), [project,setProject] = useState('');
  const [images,setImages] = useState<TissueImage[]>([]), [imageId,setImageId] = useState(localStorage.getItem('imageId') || '');
  const [rois,setRois] = useState<Roi[]>([]), [roiId,setRoiId] = useState(''), [runs,setRuns] = useState<Run[]>([]), [runId,setRunId] = useState('');
  const [cells,setCells] = useState<Cell[]>([]), [summary,setSummary] = useState<Summary|null>(null), [reviews,setReviews] = useState<Review[]>([]), [version,setVersion] = useState('latest');
  const [cellId,setCellId] = useState(''), [mode,setMode] = useState<'pan'|'roi'>('pan'), [display,setDisplay] = useState<'contour'|'points'|'off'>('contour');
  const [channels,setChannels] = useState<Record<string,boolean>>({composite:true,DAPI:false,panCK:false,CD8:false}), [opacity,setOpacity] = useState(.8);
  const [draft,setDraft] = useState<Rect>(), [roiName,setRoiName] = useState('区域 01'), [tag,setTag] = useState('tumor-candidate');
  const [panck,setPanck] = useState(.35), [cd8,setCd8] = useState(.35), [reviewLabel,setReviewLabel] = useState('excluded'), [reason,setReason] = useState('');
  const [error,setError] = useState(''), [busy,setBusy] = useState(false), [projectForm,setProjectForm] = useState(false), [newProject,setNewProject] = useState('');
  const [importOpen,setImportOpen] = useState(false), [importName,setImportName] = useState(''), [importDescription,setImportDescription] = useState(''), [importFile,setImportFile] = useState<File|null>(null);
  const [tab,setTab] = useState<'analysis'|'objects'>('analysis');
  const generation = useRef(0), resultGeneration = useRef(0);
  const image = images.find(i => i.id === imageId), roi = rois.find(r => r.id === roiId), run = runs.find(r => r.runId === runId), cell = cells.find(c => c.cellId === cellId);
  const taskActive = run?.status === 'Queued' || run?.status === 'Running';
  const act = async (fn: () => Promise<void>) => {setBusy(true);setError('');try {await fn();} catch(e) {setError((e as Error).message);} finally {setBusy(false);}};
  useEffect(() => {api<Project[]>('/projects').then(p => {setProjects(p);setProject(p[0]?.id || '');}).catch(e => setError(e.message));},[]);
  useEffect(() => {if (!project) return; let active = true; api<TissueImage[]>(`/projects/${project}/images`).then(list => {if(active) {setImages(list);setImageId(previous => list.some(i => i.id === previous) ? previous : list[0]?.id || '');}}).catch(e => {if(active)setError(e.message);}); return () => {active=false;};},[project]);
  useEffect(() => {
    const ticket = ++generation.current; ++resultGeneration.current;
    setRois([]);setRuns([]);setRoiId('');setRunId('');setCells([]);setSummary(null);setReviews([]);setDraft(undefined);setCellId('');setVersion('latest');
    if (!imageId) return; localStorage.setItem('imageId',imageId);
    Promise.all([api<Roi[]>(`/images/${imageId}/rois`),api<Run[]>(`/images/${imageId}/analysis-runs`)]).then(([r,a]) => {if(ticket!==generation.current)return;setRois(r);setRuns(a);setRunId(a[0]?.runId || '');setRoiId(a[0]?.roiId || r[0]?.id || '');}).catch(e => {if(ticket===generation.current)setError(e.message);});
  },[imageId]);
  const loadResults = useCallback(async () => {
    const ticket = ++resultGeneration.current;
    if (!runId || run?.status !== 'Succeeded') {setCells([]);setSummary(null);setReviews([]);return;}
    const query = version === 'latest' ? '' : `?reviewVersion=${version}`;
    const [c,s,r] = await Promise.all([api<Cell[]>(`/analysis-runs/${runId}/cells${query}`),api<Summary>(`/analysis-runs/${runId}/summary${query}`),api<Review[]>(`/analysis-runs/${runId}/reviews`)]);
    if(ticket!==resultGeneration.current)return;
    setCells(c);setSummary(s);setReviews(r);
  },[runId,run?.status,version]);
  useEffect(() => {loadResults().catch(e => setError(e.message)); return () => {++resultGeneration.current;};},[loadResults]);
  useEffect(() => {
    if(!taskActive || !runId)return; let active=true;
    const timer=setInterval(() => api<Run>(`/analysis-runs/${runId}`).then(r => {if(active)setRuns(old => old.map(o => o.runId===r.runId?r:o));}).catch(e => {if(active)setError(e.message);}),1200);
    return () => {active=false;clearInterval(timer);};
  },[taskActive,runId]);
  const selectRun = (id: string) => {++resultGeneration.current;setCells([]);setSummary(null);setCellId('');setRunId(id);setVersion('latest'); const selected = runs.find(r => r.runId===id); if(selected){setRoiId(selected.roiId);setPanck(selected.thresholds.panck);setCd8(selected.thresholds.cd8);}};
  const selectRoi = (r:Roi) => {setRoiId(r.id);const latest=runs.find(a=>a.roiId===r.id);selectRun(latest?.runId || '');};
  const saveRoi = () => act(async () => {if(!draft)return;const r=await post<Roi>(`/images/${imageId}/rois`,{...draft,name:roiName,regionTag:tag});setRois(old=>[...old,r]);setRoiId(r.id);selectRun('');setDraft(undefined);setMode('pan');setRoiName(`区域 ${String(rois.length+2).padStart(2,'0')}`);});
  const analyze = () => act(async () => {const r=await post<Run>('/analysis-runs',{imageId,roiId,modelVersion:'mock-unmix-v1',thresholds:{panck,cd8}});setRuns(old=>[r,...old]);setRunId(r.runId);setCells([]);setSummary(null);setVersion('latest');setCellId('');});
  const upload = () => act(async () => {if(!importFile)return;if(importFile.size>50*1024*1024)throw new Error('文件不得超过 50 MB');const data=new FormData();data.append('file',importFile);data.append('name',importName || importFile.name);data.append('description',importDescription);const i=await api<TissueImage>(`/projects/${project}/images`,{method:'POST',body:data});setImages(old=>[...old,i]);setImageId(i.id);setImportOpen(false);setImportFile(null);});
  const submitReview = () => act(async () => {await post(`/analysis-runs/${runId}/reviews`,{cellId,newLabel:reviewLabel,reason});setReason('');if(version==='latest')await loadResults();else setVersion('latest');});
  const download = () => act(async () => {const v=summary?.reviewVersion??0;const response=await fetch(`/api/analysis-runs/${runId}/export?reviewVersion=${v}`);if(!response.ok)throw new Error((await response.json()).message);const url=URL.createObjectURL(await response.blob());const a=document.createElement('a');a.href=url;a.download=`oncomosaic-${runId}-v${v}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
  const pct=(v:number|null)=>v===null?'—':(v*100).toFixed(1)+'%';
  return <div className="app">
    <header className="app-header"><a className="brand" href="/"><span className="brand-symbol"><Layers3 size={22}/></span>Onco<span>Mosaic</span><small>RESEARCH WORKSPACE</small></a><div className="header-right"><span className="demo-badge"><FlaskConical size={13}/> 合成演示数据 / 模拟模型</span><span className="local"><i/> 本地工作空间</span></div></header>
    <div className="workspace-title"><div><div className="breadcrumb">研究项目 <ChevronRight size={12}/> {projects.find(p=>p.id===project)?.name || '载入项目'}</div><h1>多标记组织细胞分析 <span>工程原型</span></h1></div><div className="notice">探索组织中的每一个信号<span>科研 / 教学演示 · 非诊断用途</span></div></div>
    {error && <div role="alert" className="error-banner">{error}<button aria-label="关闭错误" onClick={()=>setError('')}><X size={15}/></button></div>}
    <main className="workspace">
      <aside className="left-panel"><div className="panel-heading"><span><FolderOpen size={15}/> 项目图像</span><button aria-label="创建项目" onClick={()=>setProjectForm(!projectForm)}><Plus size={16}/></button></div>
        <select aria-label="项目" value={project} onChange={e=>setProject(e.target.value)}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>
        {projectForm && <form className="mini-form" onSubmit={e=>{e.preventDefault();act(async()=>{const p=await post<Project>('/projects',{name:newProject});setProjects(old=>[...old,p]);setProject(p.id);setProjectForm(false);setNewProject('');});}}><input placeholder="新项目名称" aria-label="新项目名称" value={newProject} onChange={e=>setNewProject(e.target.value)} maxLength={120} required/><button disabled={busy} className="secondary">创建项目</button></form>}
        <button className="import-button" onClick={()=>setImportOpen(true)} disabled={!project}><Upload size={15}/> 导入高光谱图像</button>
        <div className="section-label">图像资源 <span>{images.length.toString().padStart(2,'0')}</span></div>
        <div className="image-list">{images.map(i=><button key={i.id} className={'image-item '+(imageId===i.id?'selected':'')} onClick={()=>setImageId(i.id)}><img src={i.previewUrl} alt="合成组织预览"/><span><strong>{i.name}</strong><small>{i.width} × {i.height} · {i.bandCount} 波段</small></span>{imageId===i.id&&<i/>}</button>)}{!images.length&&<p className="empty-text">尚无图像，导入 NPZ 开始分析。</p>}</div>
        {image&&<><div className="section-label">图像元数据</div><dl className="metadata"><dt>尺寸</dt><dd>{image.width} × {image.height} px</dd><dt>光谱范围</dt><dd>{image.wavelengths[0]}–{image.wavelengths.at(-1)} nm</dd><dt>像素尺寸</dt><dd>{image.pixelSizeUm} µm / px</dd><dt>文件格式</dt><dd>NumPy · NPZ</dd></dl><p className="image-description">{image.description}</p></>}
        <div className="section-label">感兴趣区域 <span>{rois.length.toString().padStart(2,'0')}</span></div><div className="roi-list">{rois.map((r,index)=><button key={r.id} className={r.id===roiId?'selected':''} onClick={()=>selectRoi(r)}><BoxSelect size={14}/><span>{r.name}<small>{r.width} × {r.height} px · {r.regionTag==='tumor-candidate'?'肿瘤候选区域':'其他区域'}</small></span><b>{String(index+1).padStart(2,'0')}</b></button>)}</div><div className="left-bottom"><FlaskConical size={17}/><span>独立模拟算法<small>mock-unmix-v1</small></span></div>
      </aside>
      <section className="center-panel"><div className="toolbar"><div className="tools"><button className={mode==='pan'?'active':''} onClick={()=>setMode('pan')}><Hand size={15}/>平移</button><button className={mode==='roi'?'active':''} onClick={()=>{setMode('roi');setTab('analysis');}} disabled={!image}><BoxSelect size={15}/>矩形 ROI</button><span className="divider"/><select aria-label="细胞显示方式" value={display} onChange={e=>setDisplay(e.target.value as typeof display)}><option value="contour">核轮廓</option><option value="points">中心点</option><option value="off">隐藏细胞</option></select></div><button className="primary" onClick={analyze} disabled={!roi || busy || taskActive}>{taskActive?<LoaderCircle size={14} className="spin"/>:<Play size={13}/>}开始分析</button></div>
        {image?<Viewer key={image.id} image={image} rois={rois} selectedRoi={roi} runId={run?.status==='Succeeded'?runId:undefined} cells={cells} selectedCell={cellId} mode={mode} display={display} channels={channels} opacity={opacity} draft={draft} onDraft={setDraft} onCell={c=>{setCellId(c.cellId);setTab('objects');setReviewLabel(c.effectiveLabels);}} onRoi={selectRoi}/>:<div className="empty-view"><ImageIcon size={46}/><h2>导入一张图像，开始探索</h2><p>支持 3–64 波段的 NPZ 合成数据</p></div>}
        <div className="results"><div className="result-heading"><span><Activity size={15}/> 区域定量结果 <small>{roi?.name || '未选择区域'}</small></span><select aria-label="复核版本" value={version} onChange={e=>setVersion(e.target.value)} disabled={!summary}><option value="latest">最新复核结果{reviews.length?` · v${reviews.at(-1)?.version}`:''}</option><option value="0">原始自动结果 · v0</option>{reviews.map(r=><option key={r.version} value={r.version}>复核版本 v{r.version}</option>)}</select></div>
          <div className="metric-grid"><article><span>总核数 / 有效核数</span><strong data-testid="total-count">{summary?summary.counts.total:'—'}<small>{summary?` / ${summary.counts.valid}`:''}</small></strong><footer>{summary?`排除 ${summary.counts.excluded} 个对象`:'圈选区域后开始分析'}</footer></article><article><span>{summary?.regionTag==='tumor-candidate'?'候选肿瘤相关细胞':'panCK 阳性核对象'}</span><strong>{summary?summary.counts.panck:'—'}<small> 个</small></strong><footer>panCK 阳性比例 {summary?pct(summary.panckFraction):'—'}</footer></article><article><span>CD8 阳性密度</span><strong>{summary?summary.cd8Density.toFixed(0):'—'}<small> /mm²</small></strong><footer>CD8 阳性比例 {summary?pct(summary.cd8Fraction):'—'}</footer></article><article><span>CD8 → panCK 最近邻</span><strong>{summary?.meanNearestDistanceUm!=null?summary.meanNearestDistanceUm.toFixed(2):'—'}<small> µm</small></strong><footer>{summary?.meanNearestDistanceUm==null?'无可计算对象':'核中心最近邻距离 · 均值'}</footer></article></div>
          {summary&&<div className="distribution"><span>双标记组合</span>{[['panck',summary.counts.panckOnly],['cd8',summary.counts.cd8Only],['double-positive',summary.counts.doublePositive],['negative',summary.counts.negative]].map(([label,count])=><span key={label} className="legend-item"><i style={{background:colors[label]}}/>{labels[label]} <b>{count}</b></span>)}<div className="distribution-bar">{[['panck',summary.counts.panckOnly],['cd8',summary.counts.cd8Only],['double-positive',summary.counts.doublePositive],['negative',summary.counts.negative]].map(([label,count])=><i key={label} style={{background:colors[label],flex:Number(count)}}/>)}</div></div>}
        </div>
      </section>
      <aside className="right-panel"><div className="panel-tabs"><button className={tab==='analysis'?'active':''} onClick={()=>setTab('analysis')}><Layers3 size={14}/> 图层与分析</button><button className={tab==='objects'?'active':''} onClick={()=>setTab('objects')}><CircleDot size={14}/> 细胞详情</button></div>
        <div className="right-scroll">{tab==='analysis'?<>
          <section className="settings-section"><h3>显示通道 <small>仅影响视觉</small></h3>{[['composite','合成预览','#b7aaa8'],['DAPI','DAPI · 细胞核','#74acff'],['panCK','panCK · 模拟标记','#ffb74d'],['CD8','CD8 · 模拟标记','#42e1a7']].map(([key,label,color])=><label className="channel-row" key={key}><input type="checkbox" checked={channels[key]} disabled={key!=='composite'&&run?.status!=='Succeeded'} onChange={e=>setChannels({...channels,[key]:e.target.checked})}/><i style={{background:color}}/>{label}<span>{key==='composite'?'RGB':'0–1'}</span></label>)}<label className="range-label">通道透明度 <span>{Math.round(opacity*100)}%</span><input aria-label="通道透明度" type="range" min="0" max="1" step=".05" value={opacity} onChange={e=>setOpacity(+e.target.value)}/></label></section>
          {(draft||mode==='roi')&&<section className="settings-section roi-editor"><h3>新建矩形区域</h3><p>{draft?`X ${draft.x} · Y ${draft.y} · ${draft.width} × ${draft.height} px`:'在图像上拖动以绘制矩形。'}</p><label>区域名称<input aria-label="区域名称" value={roiName} maxLength={120} onChange={e=>setRoiName(e.target.value)}/></label><label>区域标签<select aria-label="区域标签" value={tag} onChange={e=>setTag(e.target.value)}><option value="tumor-candidate">肿瘤候选区域</option><option value="other">其他区域</option></select></label><button className="primary full" onClick={saveRoi} disabled={!draft?.width||!draft?.height||busy||!roiName.trim()}>保存 ROI</button></section>}
          <section className="settings-section"><h3>阳性判定规则 <span className="tiny-tag">0–1</span></h3><p>基于原始测量值，由服务端计算。调整后开始分析将保留新版本。</p><label className="threshold">panCK 阈值<input aria-label="panCK 阈值" type="number" min="0" max="1" step=".05" value={panck} onChange={e=>setPanck(+e.target.value)}/></label><label className="threshold">CD8 阈值<input aria-label="CD8 阈值" type="number" min="0" max="1" step=".05" value={cd8} onChange={e=>setCd8(+e.target.value)}/></label>{summary&&<p>当前结果阈值：panCK {summary.thresholds.panck} / CD8 {summary.thresholds.cd8}</p>}</section>
          <section className="settings-section"><h3>分析记录 <small>{runs.length} 次</small></h3>{runs.length?<select className="full" aria-label="分析记录" value={runId} onChange={e=>selectRun(e.target.value)}>{!runId&&<option value="">选择任务</option>}{runs.map((r,index)=><option key={r.runId} value={r.runId}>#{runs.length-index} · {statuses[r.status]} · {rois.find(roi=>roi.id===r.roiId)?.name}</option>)}</select>:<p>保存 ROI 后创建首个分析任务。</p>}{run&&<div className="run-detail"><span>{statuses[run.status]} · 第 {run.attempt} 次执行</span><code>{run.runId.slice(0,18)}…</code>{run.error&&<p className="inline-error">{run.error.message}</p>}{run.status==='Failed'&&<button className="secondary" disabled={busy} onClick={()=>act(async()=>{const r=await post<Run>(`/analysis-runs/${runId}/retry`);setRuns(old=>old.map(o=>o.runId===runId?r:o));})}><RotateCcw size={13}/>重试分析</button>}</div>}</section>
        </>:<section className="settings-section">{cell?<><h3>核对象 #{cell.localIndex}<span className="tiny-tag">{cell.qualityFlag==='ok'?'正常':'裁剪边缘'}</span></h3><p>原图坐标 ({cell.x.toFixed(2)}, {cell.y.toFixed(2)})<br/>核面积 {cell.areaPx} px²</p><div className="intensity-list">{Object.entries(cell.intensities).map(([key,value])=><div key={key}><span>{key==='dapi'?'DAPI · 核内均值':key==='panck'?'panCK · 核周近似':'CD8 · 核周近似'}</span><b>{value.toFixed(4)}</b><div><i style={{width:`${value*100}%`,background:key==='dapi'?'#74acff':key==='panck'?'#ffb74d':'#42e1a7'}}/></div></div>)}</div><dl className="cell-labels"><dt>自动类别</dt><dd>{labels[cell.autoLabels]}</dd><dt>有效类别</dt><dd>{labels[cell.effectiveLabels]}</dd></dl><h3>人工复核</h3><p>保留原始测量和自动类别，生成新的复核版本。</p><select aria-label="修正类别" className="full" value={reviewLabel} onChange={e=>setReviewLabel(e.target.value)}>{Object.entries(labels).map(([key,label])=><option value={key} key={key}>{label}</option>)}</select><textarea aria-label="复核原因" placeholder="修正原因（可选）" value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)}/><button className="primary full" onClick={submitReview} disabled={busy}>提交复核</button>{reviews.filter(r=>r.cellId===cellId).map(r=><p className="review-entry" key={r.version}>v{r.version} · {labels[r.newLabel]}<br/>{r.reason || '未填写原因'}</p>)}</>:<div className="empty-details"><CircleDot size={30}/><h3>选择一个细胞</h3><p>点击图中的核轮廓或中心点，查看强度和复核类别。</p></div>}<div className="object-list">{cells.slice(0,300).map(c=><button key={c.cellId} className={cellId===c.cellId?'selected':''} onClick={()=>{setCellId(c.cellId);setReviewLabel(c.effectiveLabels);}}><span>#{c.localIndex}</span><i style={{background:colors[c.effectiveLabels]}}/>{labels[c.effectiveLabels]}</button>)}</div></section>}
        </div><div className="export-panel"><button className="secondary full" onClick={download} disabled={!summary||busy}><ArrowDownToLine size={15}/> 导出当前版本</button><small>CSV · PNG · JSON 方法记录</small></div>
      </aside>
    </main>
    <footer className="status-bar"><span><i className={taskActive?'working':''}/>{busy?'正在处理…':run?statuses[run.status]:'工作空间已就绪'}{taskActive&&' · Python 模拟分析服务'}</span><span>{summary?`ROI ${summary.areaMm2.toFixed(6)} mm² · 复核 v${summary.reviewVersion}`:'矩形 ROI → 模拟分析 → 复核 → 导出'}<b>非诊断用途</b></span></footer>
    {importOpen&&<div className="modal-backdrop"><form className="modal" onSubmit={e=>{e.preventDefault();upload();}}><button className="modal-close" type="button" aria-label="关闭导入" onClick={()=>setImportOpen(false)}><X size={18}/></button><Upload size={25}/><h2>导入高光谱图像</h2><p>本地演示格式 .npz · 最大 50 MB<br/>需包含 cube、wavelengths_nm、pixel_size_um。</p><label>图像文件<input aria-label="图像文件" type="file" accept=".npz" required onChange={e=>{setImportFile(e.target.files?.[0]||null);setImportName(e.target.files?.[0]?.name.replace('.npz','')||'');}}/></label><label>图像名称<input aria-label="图像名称" value={importName} onChange={e=>setImportName(e.target.value)} maxLength={160} required/></label><label>说明<textarea aria-label="图像说明" value={importDescription} maxLength={2000} onChange={e=>setImportDescription(e.target.value)}/></label><button className="primary full" disabled={busy||!importFile}>{busy?'校验并导入中…':'校验并导入'}</button></form></div>}
  </div>;
}
