import { test, expect } from '@playwright/test';
import path from 'node:path';
test('upload → zoom ROI → analyze → cell review → historical export → reload',async({page})=>{
  const browserErrors:string[]=[];
  page.on('pageerror',e=>browserErrors.push(e.message));
  await page.goto('/');
  await expect(page.getByTestId('viewer')).toBeVisible();
  await page.getByRole('button',{name:'导入高光谱图像'}).click();
  await page.getByLabel('图像文件').setInputFiles(path.resolve('../data/sample-hsi.npz'));
  await page.getByLabel('图像名称',{exact:true}).fill(`浏览器验收 ${Date.now()}`);
  await page.getByRole('button',{name:'校验并导入',exact:true}).click();
  await expect(page.getByRole('heading',{name:'导入高光谱图像'})).toHaveCount(0);
  await page.getByRole('button',{name:'放大',exact:true}).click();
  await page.getByRole('button',{name:'矩形 ROI',exact:true}).click();
  const viewer=page.getByTestId('viewer');
  const box=(await viewer.boundingBox())!;
  await page.mouse.move(box.x+box.width*.27,box.y+box.height*.22);
  await page.mouse.down();
  await page.mouse.move(box.x+box.width*.7,box.y+box.height*.78,{steps:15});
  await page.mouse.up();
  await page.getByLabel('区域名称').fill('浏览器圈选区域');
  await page.getByRole('button',{name:'保存 ROI',exact:true}).click();
  await page.getByRole('button',{name:'开始分析',exact:true}).click();
  await expect(page.getByTestId('total-count')).not.toContainText('—',{timeout:45000});
  const total=await page.getByTestId('total-count').textContent();
  await page.getByLabel('DAPI · 细胞核').check();
  await expect(page.getByTestId('total-count')).toHaveText(total!);
  await page.getByLabel('细胞显示方式').selectOption('points');
  const first=page.locator('[data-testid^="cell-"]').first();
  await first.click();
  await expect(page.getByRole('heading',{name:/核对象 #/})).toBeVisible();
  await page.getByLabel('修正类别').selectOption('excluded');
  await page.getByLabel('复核原因').fill('浏览器验收：演示排除，不修改原始强度');
  await page.getByRole('button',{name:'提交复核',exact:true}).click();
  await expect(page.getByText('排除 1 个对象',{exact:true})).toBeVisible();
  await page.getByLabel('复核版本').selectOption('0');
  await expect(page.getByText('排除 0 个对象',{exact:true})).toBeVisible();
  await page.getByLabel('复核版本').selectOption('1');
  await expect(page.getByText('排除 1 个对象',{exact:true})).toBeVisible();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'导出当前版本'}).click();
  const download=await downloadPromise;
  expect(download.suggestedFilename()).toContain('-v1.zip');
  await download.saveAs(path.resolve('../.local/browser-export.zip'));
  await page.reload();
  await expect(page.getByText('排除 1 个对象',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'细胞详情',exact:true}).click();
  await page.locator('[data-testid^="cell-"]').first().click();
  await page.screenshot({path:path.resolve('../docs/browser-workflow.png'),fullPage:true});
  await page.setViewportSize({width:1366,height:768});
  await expect(page.getByTestId('viewer')).toBeVisible();
  await page.screenshot({path:path.resolve('../docs/browser-1366x768.png'),fullPage:true});
  expect(browserErrors).toEqual([]);
});
